[package]
name = "paper-shell"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.29.1"
eframe = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
font-kit = "0.14.3"
